#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-zabbix-docker-update';
event_actions ($event,
     'initialize-default-databases' => '00',
     'nethserver-zabbix-docker-conf' => '10'
);

templates2events("/etc/httpd/conf.d/zabbix.conf", $event);
event_templates($event, qw(
  /etc/httpd/conf.d/zabbix.conf
  /etc/fail2ban/filter.d/zabbix-docker.conf
  /etc/fail2ban/jail.d/01-zabbix-docker.conf  
  /opt/zabbix-docker/docker-compose.override.yml
));

event_services($event,
               'httpd' => 'reload',
               'zabbix-docker' => 'restart'
);

#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

#$event = 'pre-backup-data';

#event_actions($event, 'nethserver-zabbix-docker-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

#$event = 'post-restore-data';

#event_actions($event, 'nethserver-zabbix-docker-restore' => 50);
