#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-zabbix-update';
event_actions ($event,
     'initialize-default-databases' => '00',
     'nethserver-zabbix-docker-conf' => '10'
);

templates2events("/etc/httpd/conf.d/zabbix.conf", $event);

event_services($event,
               'httpd' => 'reload'
);


#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = 'pre-backup-data';

event_actions($event, 'nethserver-zabbix-docker-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = 'post-restore-data';

event_actions($event, 'nethserver-zabbix-docker-restore' => 50);
