#!/bin/bash

#su - postgres -c "pg_dump zabbix > /var/lib/nethserver/zabbix/backup/zabbix.sql"
docker exec -i zabbix-docker-postgres-server-1 pg_dump -U zabbix -d zabbix > /var/lib/nethserver/zabbix-docker/backup/zabbix.sql >/dev/null
