#!/bin/bash

# do not restore DB by SQL, try docker instead
exit 0

if [ -f /var/lib/nethserver/zabbix-docker/backup/zabbix.sql ]; then
  docker stop $(docker ps -aqf "name=zabbix-docker-zabbix-server-1")
  tmp_sql=`mktemp`
  chmod a+r $tmp_sql
  cat << EOF > $tmp_sql
UPDATE pg_database SET datallowconn = 'false' WHERE datname = 'zabbix';
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'zabbix';
DROP DATABASE zabbix;
CREATE database zabbix;
CREATE USER zabbix WITH PASSWORD 'zabbix'; GRANT ALL PRIVILEGES ON DATABASE zabbix to zabbix;
UPDATE pg_database SET datallowconn = 'true' WHERE datname = 'zabbix';
EOF
  docker exec -i zabbix-docker-postgres-server-1 psql -U zabbix -d postgres < $tmp_sql >/dev/null
  docker exec -i zabbix-docker-postgres-server-1 psql -U zabbix -d zabbix < /var/lib/nethserver/zabbix-docker/backup/zabbix.sql >/dev/null
  rm -f $tmp_sql
  docker start $(docker ps -aqf "name=zabbix-docker-zabbix-server-1")
fi
